# Generated by Django 3.1.4 on 2020-12-14 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_url', models.CharField(max_length=150)),
                ('image_class', models.CharField(max_length=50)),
                ('image_percentaje', models.FloatField()),
            ],
        ),
    ]
